packages:
  - 'server'
  - 'client-react'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@tsparticles/engine': true
  electron-winstaller: true
  esbuild: true
  msw: true
  prisma: true
